Can pass this to runSnippetInTab() to run previous code snippet
nre-learning/antidote-web pull request #45
Opened 2019-03-27 08:52 UTC by jnpr-raylam

To avoid batch update the index in "Run this snippet" for insertion/removal of single snippet, suggest to modify the code, so that it accepts either an index or `this` object so it doesn't break existing lab guide content.

After the change, we can pass the index as usual:
```
<button type="button" class="btn btn-primary btn-sm" onclick="runSnippetInTab('vqfx', 0)">Run this snippet</button>
```

or pass `this` object:
```
<button type="button" class="btn btn-primary btn-sm" onclick="runSnippetInTab('vqfx', this)">Run this snippet</button>
```
and it will run the previous snippet just before the button object.

2019-04-14 07:00 UTC, Mierdin requested changes
Just one comment below. Also, please add a CHANGELOG entry. Overall though, this is great work! Will make things much simpler in lesson guides.

2019-04-14 07:00 UTC, Mierdin commented on src/main/webapp/js/antidote.js
> +    } else if (typeof snippetIndex == 'object') {
```suggestion
    } else {
```

Let's just catch all non-number cases here. If there's an issue accessing the object fields, that will get popped up to the javascript console.

2019-04-17 14:46 UTC, jnpr-raylam commented on src/main/webapp/js/antidote.js
> +    } else if (typeof snippetIndex == 'object') {
Applied the change according to your suggestion, and updated the CHANGELOG as well.

2019-04-19 20:12 UTC, Mierdin commented
Excellent, thanks. I'd like to also update the nrelabs curriculum to use this (even though it's not strictly required based on your code here) so that people that look at other lessons for inspiration can see this as the de facto standard.

Since this will result in a fairly big change (and v0.3.2 is out today) I'll merge this for the v0.4.0 release.

2019-04-21 19:33 UTC, merged